# Generated by Django 6.0.4 on 2026-10-05 20:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_social_achievements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TavernMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal. Ver documentación de diseño para justificación.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación. Inmutable post-creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación. Gestionado automáticamente.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indica un registro borrado lógicamente (soft delete).')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp del borrado lógico. NULL = registro activo.', null=True)),
                ('content', models.CharField(max_length=280)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tavern_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tavern Message',
                'verbose_name_plural': 'Tavern Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TavernReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal. Ver documentación de diseño para justificación.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación. Inmutable post-creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación. Gestionado automáticamente.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indica un registro borrado lógicamente (soft delete).')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp del borrado lógico. NULL = registro activo.', null=True)),
                ('reaction', models.CharField(max_length=20)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='community.tavernmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tavern_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tavern Reaction',
                'verbose_name_plural': 'Tavern Reactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tavernmessage',
            index=models.Index(fields=['user', '-created_at'], name='community_t_user_id_7842e7_idx'),
        ),
        migrations.AddIndex(
            model_name='tavernreaction',
            index=models.Index(fields=['user', '-created_at'], name='community_t_user_id_cea83d_idx'),
        ),
    ]
