# Generated by Django 6.0.4 on 2026-10-05 22:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_tavernmessage_tavernreaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TavernInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal. Ver documentación de diseño para justificación.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación. Inmutable post-creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación. Gestionado automáticamente.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indica un registro borrado lógicamente (soft delete).')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp del borrado lógico. NULL = registro activo.', null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tavern_invites_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tavern_invites_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('sender', 'recipient'), name='unique_active_tavern_invite'), models.CheckConstraint(condition=models.Q(('sender', models.F('recipient')), _negated=True), name='tavern_invite_not_self')],
            },
        ),
    ]
