# Generated by Django 6.0.4 on 2026-09-19 00:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0022_book_word_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal. Ver documentación de diseño para justificación.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación. Inmutable post-creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación. Gestionado automáticamente.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indica un registro borrado lógicamente (soft delete).')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp del borrado lógico. NULL = registro activo.', null=True)),
                ('level_number', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('difficulty', models.CharField(choices=[('facil', 'Fácil'), ('intermedio', 'Intermedio'), ('dificil', 'Difícil')], default='facil', max_length=20)),
                ('required_score', models.PositiveIntegerField(default=70, help_text='Porcentaje de aciertos necesario para aprobar (ej. 70%).')),
                ('xp_reward', models.PositiveIntegerField(default=30)),
                ('ink_reward', models.PositiveIntegerField(default=10)),
                ('is_exam', models.BooleanField(default=False, help_text='Prueba final de la unidad.')),
                ('is_chest', models.BooleanField(default=False, help_text='Nodo de cofre con recompensa extra.')),
                ('icon', models.CharField(default='auto_stories', max_length=50)),
            ],
            options={
                'verbose_name': 'Learning Level',
                'verbose_name_plural': 'Learning Levels',
                'ordering': ['unit__unit_number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LearningUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal. Ver documentación de diseño para justificación.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación. Inmutable post-creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación. Gestionado automáticamente.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indica un registro borrado lógicamente (soft delete).')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp del borrado lógico. NULL = registro activo.', null=True)),
                ('unit_number', models.PositiveIntegerField(unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=1)),
                ('icon', models.CharField(default='menu_book', max_length=50)),
                ('banner_color', models.CharField(default='#3b82f6', max_length=30)),
                ('min_user_level', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Learning Unit',
                'verbose_name_plural': 'Learning Units',
                'ordering': ['unit_number'],
            },
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal. Ver documentación de diseño para justificación.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación. Inmutable post-creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación. Gestionado automáticamente.')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp del borrado lógico. NULL = registro activo.', null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('item_type', models.CharField(choices=[('streak_shield', 'Protector de Racha'), ('streak_repair', 'Poción de Recuperación de Racha'), ('hearts_refill', 'Recarga de Corazones'), ('profile_frame', 'Marco de Perfil'), ('theme', 'Tema Visual'), ('title', 'Título Honorífico')], max_length=30)),
                ('cost_ink', models.PositiveIntegerField(default=50)),
                ('icon', models.CharField(default='shopping_bag', max_length=50)),
                ('asset_url', models.CharField(blank=True, default='', max_length=255)),
                ('value', models.CharField(blank=True, default='', help_text="Identificador técnico aplicado al equipar (ej. 'frame-gold', 'title-erudite').", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Shop Item',
                'verbose_name_plural': 'Shop Items',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LearningExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal. Ver documentación de diseño para justificación.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación. Inmutable post-creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación. Gestionado automáticamente.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indica un registro borrado lógicamente (soft delete).')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp del borrado lógico. NULL = registro activo.', null=True)),
                ('title', models.CharField(max_length=200)),
                ('author_name', models.CharField(blank=True, default='', max_length=150)),
                ('source_type', models.CharField(choices=[('classic_book', 'Obra Clásica del Catálogo'), ('pedagogic_original', 'Ficción Pedagógica Original')], default='classic_book', max_length=30)),
                ('content_pages', models.JSONField(default=list, help_text='Lista de páginas de texto del pasaje a leer.')),
                ('questions_data', models.JSONField(default=list, help_text='Lista de preguntas estructuradas con opciones, explicaciones y tipo.')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_exercises', to='catalog.book')),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='learning.learninglevel')),
            ],
            options={
                'verbose_name': 'Learning Exercise',
                'verbose_name_plural': 'Learning Exercises',
            },
        ),
        migrations.AddField(
            model_name='learninglevel',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='learning.learningunit'),
        ),
        migrations.CreateModel(
            name='UserExerciseAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal. Ver documentación de diseño para justificación.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación. Inmutable post-creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación. Gestionado automáticamente.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indica un registro borrado lógicamente (soft delete).')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp del borrado lógico. NULL = registro activo.', null=True)),
                ('score', models.PositiveSmallIntegerField(default=0, help_text='Porcentaje de acierto obtenido.')),
                ('passed', models.BooleanField(default=False)),
                ('answers_log', models.JSONField(default=list, help_text='Detalle de respuestas seleccionadas.')),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('ink_earned', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('hearts_lost', models.PositiveSmallIntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.learninglevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exercise Attempt',
                'verbose_name_plural': 'Exercise Attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal. Ver documentación de diseño para justificación.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación. Inmutable post-creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación. Gestionado automáticamente.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indica un registro borrado lógicamente (soft delete).')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp del borrado lógico. NULL = registro activo.', null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_equipped', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='learning.shopitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Inventory Item',
                'verbose_name_plural': 'User Inventory Items',
            },
        ),
        migrations.CreateModel(
            name='UserLevelProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal. Ver documentación de diseño para justificación.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación. Inmutable post-creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación. Gestionado automáticamente.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indica un registro borrado lógicamente (soft delete).')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp del borrado lógico. NULL = registro activo.', null=True)),
                ('stars', models.PositiveSmallIntegerField(default=0, help_text='Estrellas obtenidas (0 a 3).')),
                ('best_score', models.PositiveSmallIntegerField(default=0, help_text='Mejor porcentaje de acierto registrado (0 a 100).')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.learninglevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Level Progress',
                'verbose_name_plural': 'User Level Progresses',
            },
        ),
        migrations.CreateModel(
            name='DailyActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal. Ver documentación de diseño para justificación.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación. Inmutable post-creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación. Gestionado automáticamente.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indica un registro borrado lógicamente (soft delete).')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp del borrado lógico. NULL = registro activo.', null=True)),
                ('date', models.DateField(db_index=True)),
                ('chapters_read', models.PositiveIntegerField(default=0)),
                ('levels_completed', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('ink_earned', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Activity Log',
                'verbose_name_plural': 'Daily Activity Logs',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_user_daily_activity')],
            },
        ),
        migrations.AddConstraint(
            model_name='learninglevel',
            constraint=models.UniqueConstraint(fields=('unit', 'level_number'), name='unique_unit_level_number'),
        ),
        migrations.AddConstraint(
            model_name='userinventoryitem',
            constraint=models.UniqueConstraint(fields=('user', 'item'), name='unique_user_shop_item'),
        ),
        migrations.AddConstraint(
            model_name='userlevelprogress',
            constraint=models.UniqueConstraint(fields=('user', 'level'), name='unique_user_level_progress'),
        ),
    ]
