# Generated by Django 6.0.4 on 2026-10-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='item_type',
            field=models.CharField(choices=[('streak_shield', 'Protector de Racha'), ('streak_repair', 'Poción de Recuperación de Racha'), ('hearts_refill', 'Recarga de Corazones'), ('profile_frame', 'Marco de Perfil'), ('theme', 'Tema Visual'), ('title', 'Título Honorífico'), ('maguito_wear', 'Accesorio de Maguito')], max_length=30),
        ),
    ]
