"""
Bancos de juegos por tema. Cada unidad toma de su tema el material para:
  pairs      → "Une las parejas" y preguntas de concepto (concepto, definición)
  classify   → "Clasifica" (categorías y elementos con el índice de su categoría)
  true_false → "Relámpago" (afirmación, verdadera o falsa)
  scramble   → "Anagrama" (palabra, pista)
  sentences  → "Reconstruye la frase"

Los datos sobre autores, obras y fechas están verificados: si se agrega algo nuevo,
debe ser igual de comprobable.
"""

BANKS = {
    'comprension': {
        'pairs_prompt': 'Une cada concepto de lectura con su definición.',
        'pairs': [
            ('Tema', 'De qué trata el texto, en pocas palabras.'),
            ('Idea principal', 'El mensaje más importante que transmite el texto.'),
            ('Detalle', 'Dato que apoya o amplía la idea principal.'),
            ('Protagonista', 'Personaje central de la historia.'),
            ('Título', 'Nombre que anticipa el contenido del texto.'),
            ('Párrafo', 'Grupo de oraciones que desarrollan una misma idea.'),
        ],
        'classify': {
            'prompt': 'Clasifica cada frase: ¿es un hecho comprobable o una opinión?',
            'categories': ['Hecho', 'Opinión'],
            'items': [
                ('El faro mide treinta metros de altura.', 0),
                ('Es el faro más hermoso de la costa.', 1),
                ('La feria abrió a las diez de la mañana.', 0),
                ('Leer poesía es aburrido.', 1),
                ('Cervantes publicó la primera parte del Quijote en 1605.', 0),
                ('Ese final fue decepcionante.', 1),
            ],
            'explanation': 'Un hecho se puede comprobar con datos; una opinión expresa un juicio personal.',
        },
        'true_false': [
            ('La idea principal suele poder resumirse en una sola oración.', True),
            ('Un detalle secundario es siempre lo más importante del texto.', False),
            ('Una opinión expresa un juicio personal que no se puede comprobar.', True),
            ('Un hecho puede verificarse con datos o fuentes.', True),
            ('El título nunca da pistas sobre el contenido.', False),
            ('Releer un párrafo difícil ayuda a comprenderlo.', True),
        ],
        'scramble': [
            ('protagonista', 'Personaje central de una historia'),
            ('opinión', 'Juicio personal que no se puede comprobar'),
            ('resumen', 'Versión breve de un texto con sus ideas clave'),
        ],
        'sentences': [
            'La idea principal es el corazón del texto.',
            'Un buen lector se pregunta qué quiso decir el autor.',
            'Los hechos se comprueban y las opiniones se discuten.',
        ],
    },
    'vocabulario': {
        'pairs_prompt': 'Une cada palabra con su significado.',
        'pairs': [
            ('Taciturno', 'Callado y reservado, de pocas palabras.'),
            ('Efímero', 'Que dura muy poco tiempo.'),
            ('Ávido', 'Que desea algo con mucha intensidad.'),
            ('Lóbrego', 'Oscuro, sombrío y triste.'),
            ('Diáfano', 'Claro, transparente, que deja pasar la luz.'),
            ('Menguar', 'Disminuir o hacerse más pequeño.'),
        ],
        'classify': {
            'prompt': 'Agrupa cada palabra según la idea de la que es sinónimo.',
            'categories': ['Alegría', 'Tristeza', 'Valentía'],
            'items': [
                ('Jubiloso', 0), ('Dichoso', 0),
                ('Afligido', 1), ('Melancólico', 1),
                ('Intrépido', 2), ('Audaz', 2),
            ],
            'explanation': 'Los sinónimos comparten un significado parecido: jubiloso y dichoso expresan alegría; afligido y melancólico, tristeza; intrépido y audaz, valentía.',
        },
        'true_false': [
            ('«Efímero» significa que dura para siempre.', False),
            ('Las palabras polisémicas tienen varios significados.', True),
            ('«Banco» puede ser un asiento o una entidad financiera.', True),
            ('Un antónimo es una palabra de significado opuesto.', True),
            ('«Lóbrego» es sinónimo de luminoso.', False),
            ('El contexto ayuda a deducir el significado de una palabra desconocida.', True),
        ],
        'scramble': [
            ('efímero', 'Que dura muy poco'),
            ('umbral', 'Entrada de una casa'),
            ('sinónimo', 'Palabra de significado parecido a otra'),
        ],
        'sentences': [
            'El contexto ilumina las palabras que no conocemos.',
            'Una misma palabra puede tener varios significados.',
            'El diccionario es el mejor amigo del lector curioso.',
        ],
    },
    'personajes': {
        'pairs_prompt': 'Une cada término con su definición.',
        'pairs': [
            ('Protagonista', 'Personaje principal, en torno a quien gira la historia.'),
            ('Antagonista', 'Personaje que se opone al protagonista.'),
            ('Personaje secundario', 'Acompaña o ayuda, sin ser el centro de la historia.'),
            ('Motivación', 'Razón que empuja a un personaje a actuar.'),
            ('Arquetipo', 'Modelo de personaje que se repite en muchas historias.'),
            ('Dilema', 'Situación en que hay que elegir entre dos opciones difíciles.'),
        ],
        'classify': {
            'prompt': 'Clasifica a estos personajes clásicos según su papel en su obra.',
            'categories': ['Protagonista', 'Antagonista', 'Secundario'],
            'items': [
                ('Don Quijote', 0), ('Alicia, en el país de las maravillas', 0),
                ('El capitán Garfio', 1), ('El conde Drácula', 1),
                ('Sancho Panza', 2), ('El doctor Watson', 2),
            ],
            'explanation': 'Don Quijote y Alicia protagonizan sus historias; Garfio y Drácula se oponen a los héroes; Sancho y Watson acompañan al protagonista.',
        },
        'true_false': [
            ('El antagonista es quien se opone al protagonista.', True),
            ('Sancho Panza es el escudero de don Quijote.', True),
            ('Un personaje secundario nunca puede influir en la trama.', False),
            ('La motivación explica por qué actúa un personaje.', True),
            ('El capitán Garfio es el mejor amigo de Peter Pan.', False),
            ('Un personaje plano cambia profundamente a lo largo de la historia.', False),
        ],
        'scramble': [
            ('héroe', 'Protagonista valiente que supera pruebas'),
            ('villano', 'Personaje malvado de una historia'),
            ('escudero', 'Sirviente que acompaña a un caballero'),
        ],
        'sentences': [
            'Todo personaje quiere algo y algo se lo impide.',
            'El antagonista pone a prueba al héroe.',
            'Los secundarios también tienen su propia historia.',
        ],
    },
    'secuencia': {
        'pairs_prompt': 'Une cada parte o recurso narrativo con su definición.',
        'pairs': [
            ('Inicio', 'Presenta personajes, lugar y situación.'),
            ('Nudo', 'Parte donde surge y crece el conflicto.'),
            ('Desenlace', 'Parte final donde se resuelve el conflicto.'),
            ('Clímax', 'Momento de mayor tensión de la historia.'),
            ('Detonante', 'Hecho que pone en marcha la historia.'),
            ('Analepsis', 'Salto hacia el pasado dentro del relato.'),
        ],
        'classify': {
            'prompt': 'Clasifica cada conector: ¿indica tiempo o consecuencia?',
            'categories': ['Tiempo', 'Consecuencia'],
            'items': [
                ('Después', 0), ('Mientras tanto', 0), ('Al amanecer', 0),
                ('Por eso', 1), ('Por lo tanto', 1), ('En consecuencia', 1),
            ],
            'explanation': 'Los conectores temporales ordenan los hechos; los consecutivos muestran qué provocó cada cosa.',
        },
        'true_false': [
            ('El desenlace es la parte donde se resuelve el conflicto.', True),
            ('El clímax ocurre siempre en la primera línea del cuento.', False),
            ('Una analepsis lleva la narración hacia el pasado.', True),
            ('«Por eso» es un conector que indica consecuencia.', True),
            ('El nudo presenta a los personajes por primera vez.', False),
            ('Una prolepsis anticipa hechos que ocurrirán después.', True),
        ],
        'scramble': [
            ('clímax', 'Momento de mayor tensión'),
            ('desenlace', 'Final donde se resuelve el conflicto'),
            ('nudo', 'Parte donde crece el conflicto'),
        ],
        'sentences': [
            'Primero ocurre el detonante y luego crece el conflicto.',
            'El desenlace resuelve lo que el nudo complicó.',
            'Cada causa deja una huella en la historia.',
        ],
    },
    'inferencia': {
        'pairs_prompt': 'Une cada concepto con su definición.',
        'pairs': [
            ('Inferir', 'Deducir algo que el texto no dice directamente.'),
            ('Subtexto', 'Lo que se comunica sin decirlo de forma explícita.'),
            ('Ironía', 'Decir lo contrario de lo que se quiere dar a entender.'),
            ('Indicio', 'Pista que permite adivinar algo.'),
            ('Explícito', 'Que se dice de manera clara y directa.'),
            ('Implícito', 'Que se entiende sin estar dicho.'),
        ],
        'classify': {
            'prompt': '¿Qué emoción sugiere cada gesto?',
            'categories': ['Nerviosismo', 'Alegría', 'Tristeza'],
            'items': [
                ('Se mordía las uñas sin parar.', 0),
                ('Tamborileaba con los dedos sobre la mesa.', 0),
                ('Silbaba mientras cruzaba la plaza.', 1),
                ('Aplaudió dando saltitos.', 1),
                ('Guardó la carta y miró por la ventana en silencio.', 2),
                ('Dejó el plato sin tocar.', 2),
            ],
            'explanation': 'Los gestos revelan emociones que el texto no nombra: eso es inferir.',
        },
        'true_false': [
            ('Inferir es deducir información que no aparece escrita.', True),
            ('Todo lo importante de un cuento se dice siempre de manera explícita.', False),
            ('La ironía dice lo contrario de lo que se quiere dar a entender.', True),
            ('Los gestos de un personaje pueden revelar sus emociones.', True),
            ('Una inferencia correcta se apoya en pistas del texto.', True),
            ('Inferir es lo mismo que inventar sin pruebas.', False),
        ],
        'scramble': [
            ('indicio', 'Pista que ayuda a deducir'),
            ('ironía', 'Decir lo contrario de lo que se piensa'),
            ('deducir', 'Sacar una conclusión a partir de pistas'),
        ],
        'sentences': [
            'Leer entre líneas es escuchar lo que el texto calla.',
            'Toda buena inferencia se apoya en una pista.',
            'Los gestos hablan cuando los personajes callan.',
        ],
    },
    'analisis': {
        'pairs_prompt': 'Une cada concepto de análisis con su definición.',
        'pairs': [
            ('Metáfora', 'Nombra una cosa con el nombre de otra por su parecido.'),
            ('Símbolo', 'Objeto o imagen que representa una idea.'),
            ('Tono', 'Actitud emocional del texto: alegre, irónico, nostálgico...'),
            ('Tema universal', 'Asunto que interesa en todas las épocas, como el amor o la muerte.'),
            ('Crítica social', 'Denuncia de problemas de la sociedad en una obra.'),
            ('Contexto histórico', 'Época y circunstancias en que se escribió la obra.'),
        ],
        'classify': {
            'prompt': 'Clasifica cada símbolo según la idea que suele representar.',
            'categories': ['Paso del tiempo', 'Libertad'],
            'items': [
                ('Un reloj de arena', 0), ('Las hojas que caen en otoño', 0), ('Una vela que se consume', 0),
                ('Un pájaro que sale de su jaula', 1), ('El mar abierto', 1), ('Unas cadenas rotas', 1),
            ],
            'explanation': 'Un símbolo representa una idea más allá de sí mismo: lo que se gasta habla del tiempo; lo que se abre o se rompe, de libertad.',
        },
        'true_false': [
            ('Un símbolo representa una idea más allá de sí mismo.', True),
            ('El tono de un texto no influye en cómo lo sentimos.', False),
            ('El amor y la muerte son temas universales.', True),
            ('El contexto histórico ayuda a entender una obra.', True),
            ('Una metáfora siempre usa la palabra «como».', False),
            ('La crítica social denuncia problemas de su tiempo.', True),
        ],
        'scramble': [
            ('símbolo', 'Imagen que representa una idea'),
            ('metáfora', 'Identifica una cosa con otra'),
            ('tono', 'Actitud emocional del texto'),
        ],
        'sentences': [
            'Un símbolo dice más de lo que muestra.',
            'El tono tiñe cada palabra del texto.',
            'Toda obra conversa con su tiempo.',
        ],
    },
    'generos': {
        'pairs_prompt': 'Une cada género o forma con su definición.',
        'pairs': [
            ('Género narrativo', 'Cuenta una historia con narrador, personajes y acciones.'),
            ('Género lírico', 'Expresa sentimientos y emociones, a menudo en verso.'),
            ('Género dramático', 'Se escribe para ser representado por actores.'),
            ('Novela', 'Relato extenso en prosa, con muchos personajes y hechos.'),
            ('Cuento', 'Relato breve, con pocos personajes y un solo conflicto.'),
            ('Acotación', 'Indicación del autor teatral sobre gestos, lugares o movimientos.'),
        ],
        'classify': {
            'prompt': 'Clasifica cada forma literaria según su género.',
            'categories': ['Narrativo', 'Lírico', 'Dramático'],
            'items': [
                ('Novela', 0), ('Cuento', 0),
                ('Soneto', 1), ('Oda', 1),
                ('Tragedia', 2), ('Comedia', 2),
            ],
            'explanation': 'La novela y el cuento narran; el soneto y la oda expresan sentimientos en verso; la tragedia y la comedia se representan.',
        },
        'true_false': [
            ('El teatro pertenece al género dramático.', True),
            ('El cuento es más extenso que la novela.', False),
            ('La poesía lírica expresa los sentimientos del hablante.', True),
            ('Las acotaciones indican cómo actúan los personajes en escena.', True),
            ('La fábula pertenece al género lírico.', False),
            ('En el género narrativo hay un narrador que cuenta los hechos.', True),
        ],
        'scramble': [
            ('novela', 'Relato largo en prosa'),
            ('poema', 'Obra escrita en verso'),
            ('comedia', 'Obra teatral de final feliz'),
        ],
        'sentences': [
            'El narrador cuenta, el poeta siente y el actor representa.',
            'Cada género tiene su propia manera de mirar el mundo.',
            'Una obra de teatro nace para subir al escenario.',
        ],
    },
    'figuras': {
        'pairs_prompt': 'Une cada figura retórica con su definición.',
        'pairs': [
            ('Símil', 'Compara dos cosas usando «como» o «cual».'),
            ('Metáfora', 'Identifica una cosa con otra sin usar nexo.'),
            ('Personificación', 'Da cualidades humanas a animales u objetos.'),
            ('Hipérbole', 'Exagera algo para darle fuerza.'),
            ('Anáfora', 'Repite una palabra al inicio de varios versos o frases.'),
            ('Onomatopeya', 'Imita un sonido con palabras.'),
        ],
        'classify': {
            'prompt': 'Clasifica cada ejemplo según la figura que usa.',
            'categories': ['Símil', 'Metáfora', 'Personificación'],
            'items': [
                ('Sus ojos eran como dos luceros.', 0),
                ('Rápido como el viento.', 0),
                ('Tus dientes, perlas blancas.', 1),
                ('El río es una serpiente de plata.', 1),
                ('El viento susurraba secretos.', 2),
                ('La luna se asomó curiosa.', 2),
            ],
            'explanation': 'El símil usa «como»; la metáfora identifica sin nexo; la personificación da rasgos humanos a lo que no lo es.',
        },
        'true_false': [
            ('«Te lo he dicho un millón de veces» es una hipérbole.', True),
            ('La personificación da rasgos humanos a lo que no es humano.', True),
            ('«Tic, tac» es una onomatopeya.', True),
            ('El símil nunca usa la palabra «como».', False),
            ('«Tus labios son rubíes» es un símil.', False),
            ('La anáfora repite palabras al comienzo de versos o frases.', True),
        ],
        'scramble': [
            ('hipérbole', 'Exageración expresiva'),
            ('símil', 'Comparación que usa «como»'),
            ('anáfora', 'Repetición al inicio de versos'),
        ],
        'sentences': [
            'La luna es un farol que cuelga del cielo.',
            'El viento cantaba entre los árboles dormidos.',
            'Tenía tanta hambre que se comería una montaña.',
        ],
    },
    'poesia': {
        'pairs_prompt': 'Une cada término de métrica con su definición.',
        'pairs': [
            ('Verso', 'Cada una de las líneas de un poema.'),
            ('Estrofa', 'Grupo de versos que forman una unidad.'),
            ('Rima consonante', 'Coinciden vocales y consonantes desde la última vocal acentuada.'),
            ('Rima asonante', 'Coinciden solo las vocales desde la última vocal acentuada.'),
            ('Soneto', 'Catorce versos endecasílabos: dos cuartetos y dos tercetos.'),
            ('Sinalefa', 'Unión en una sílaba de la vocal final de una palabra y la inicial de la siguiente.'),
        ],
        'classify': {
            'prompt': 'Clasifica cada verso: ¿de arte menor (hasta 8 sílabas) o de arte mayor (9 o más)?',
            'categories': ['Arte menor', 'Arte mayor'],
            'items': [
                ('Hexasílabo', 0), ('Heptasílabo', 0), ('Octosílabo', 0),
                ('Decasílabo', 1), ('Endecasílabo', 1), ('Alejandrino', 1),
            ],
            'explanation': 'Los versos de arte menor tienen hasta ocho sílabas; los de arte mayor, nueve o más (el alejandrino tiene catorce).',
        },
        'true_false': [
            ('Un soneto tiene catorce versos.', True),
            ('El romance usa versos octosílabos.', True),
            ('«Canción» y «razón» riman en consonante.', True),
            ('«Casa» y «mala» riman en consonante.', False),
            ('Los versos de arte menor tienen ocho sílabas o menos.', True),
            ('Una estrofa es una sola palabra de un poema.', False),
        ],
        'scramble': [
            ('verso', 'Cada línea de un poema'),
            ('estrofa', 'Grupo de versos'),
            ('soneto', 'Poema de catorce versos'),
        ],
        'sentences': [
            'Cada verso es un paso en el camino del poema.',
            'La rima hace que las palabras se den la mano.',
            'Un soneto tiene catorce versos bien medidos.',
        ],
    },
    'teatro': {
        'pairs_prompt': 'Une cada término teatral con su definición.',
        'pairs': [
            ('Acto', 'Gran parte en que se divide una obra teatral.'),
            ('Escena', 'Parte de un acto marcada por la entrada o salida de personajes.'),
            ('Acotación', 'Indicación del autor sobre gestos, lugar o movimientos.'),
            ('Monólogo', 'Un personaje habla solo, en voz alta, consigo mismo.'),
            ('Aparte', 'Lo que un personaje dice al público sin que los demás lo oigan.'),
            ('Diálogo', 'Conversación entre dos o más personajes.'),
        ],
        'classify': {
            'prompt': 'Clasifica cada rasgo: ¿es propio de la tragedia o de la comedia?',
            'categories': ['Tragedia', 'Comedia'],
            'items': [
                ('Final desdichado para el protagonista', 0),
                ('Personajes enfrentados a un destino inevitable', 0),
                ('Temas graves como la muerte y el honor', 0),
                ('Enredos y equívocos que hacen reír', 1),
                ('Final feliz', 1),
                ('Personajes cotidianos con defectos exagerados', 1),
            ],
            'explanation': 'La tragedia conmueve con conflictos graves y finales desdichados; la comedia divierte con enredos y termina bien.',
        },
        'true_false': [
            ('Las acotaciones suelen escribirse entre paréntesis.', True),
            ('En el aparte, todos los personajes escuchan lo que se dice.', False),
            ('Una obra de teatro se divide en actos y escenas.', True),
            ('El monólogo es una conversación entre muchos personajes.', False),
            ('«Romeo y Julieta» es una tragedia de Shakespeare.', True),
            ('«La vida es sueño» fue escrita por Calderón de la Barca.', True),
        ],
        'scramble': [
            ('escena', 'Parte de un acto'),
            ('telón', 'Cortina del escenario'),
            ('diálogo', 'Conversación entre personajes'),
        ],
        'sentences': [
            'El telón se abre y los personajes cobran vida.',
            'Las acotaciones son la voz del autor en escena.',
            'Un aparte es un secreto compartido con el público.',
        ],
    },
    'mitos': {
        'pairs_prompt': 'Une cada nombre o concepto con su descripción.',
        'pairs': [
            ('Mito', 'Relato sagrado que explica el origen del mundo o de la naturaleza.'),
            ('Leyenda', 'Relato tradicional de un lugar que mezcla hechos reales y fantásticos.'),
            ('Zeus', 'Dios griego del cielo y el rayo, rey del Olimpo.'),
            ('Poseidón', 'Dios griego del mar.'),
            ('Ícaro', 'Joven que voló demasiado cerca del sol con alas de cera.'),
            ('Prometeo', 'Titán que robó el fuego a los dioses para dárselo a los humanos.'),
        ],
        'classify': {
            'prompt': 'Clasifica a cada figura de la mitología griega.',
            'categories': ['Dios o diosa', 'Héroe'],
            'items': [
                ('Zeus', 0), ('Atenea', 0), ('Poseidón', 0),
                ('Heracles', 1), ('Aquiles', 1), ('Ulises', 1),
            ],
            'explanation': 'Zeus, Atenea y Poseidón son dioses del Olimpo; Heracles, Aquiles y Ulises son héroes de la mitología griega.',
        },
        'true_false': [
            ('Los mitos buscaban explicar el origen de las cosas.', True),
            ('Poseidón era el dios griego del mar.', True),
            ('Ícaro voló con alas de metal.', False),
            ('Prometeo robó el fuego para entregárselo a los humanos.', True),
            ('Las leyendas suelen estar ligadas a un lugar concreto.', True),
            ('Zeus era el dios griego del inframundo.', False),
        ],
        'scramble': [
            ('mito', 'Relato que explica un origen'),
            ('leyenda', 'Relato tradicional de un lugar'),
            ('olimpo', 'Monte donde vivían los dioses griegos'),
        ],
        'sentences': [
            'Los mitos explicaban el mundo antes que la ciencia.',
            'Cada pueblo guarda sus leyendas como un tesoro.',
            'Ícaro voló tan alto que el sol derritió sus alas.',
        ],
    },
    'fabulas': {
        'pairs_prompt': 'Une cada nombre o concepto con su descripción.',
        'pairs': [
            ('Fábula', 'Relato breve, a menudo con animales, que deja una enseñanza.'),
            ('Moraleja', 'Enseñanza que se desprende de una fábula.'),
            ('Esopo', 'Fabulista de la antigua Grecia.'),
            ('La Fontaine', 'Fabulista francés del siglo XVII.'),
            ('Samaniego', 'Fabulista español del siglo XVIII.'),
            ('Iriarte', 'Autor español de las «Fábulas literarias».'),
        ],
        'classify': {
            'prompt': 'Clasifica lo que representa cada personaje de fábula.',
            'categories': ['Virtud', 'Defecto'],
            'items': [
                ('La constancia de la tortuga', 0),
                ('La previsión de la hormiga', 0),
                ('El ingenio del cuervo con la vasija', 0),
                ('La vanidad del cuervo que deja caer el queso', 1),
                ('La soberbia de la liebre', 1),
                ('La imprevisión de la cigarra', 1),
            ],
            'explanation': 'En las fábulas cada animal encarna una virtud o un defecto humano.',
        },
        'true_false': [
            ('Las fábulas suelen terminar con una moraleja.', True),
            ('En «La liebre y la tortuga», gana la liebre.', False),
            ('Esopo fue un fabulista de la antigua Grecia.', True),
            ('En las fábulas los animales suelen actuar como personas.', True),
            ('La moraleja es el título de la fábula.', False),
            ('En «La cigarra y la hormiga», la hormiga guarda comida para el invierno.', True),
        ],
        'scramble': [
            ('moraleja', 'Enseñanza final de una fábula'),
            ('fábula', 'Relato breve con enseñanza'),
            ('tortuga', 'Ganó la carrera por su constancia'),
        ],
        'sentences': [
            'Poco a poco se llega lejos.',
            'La moraleja es el regalo que deja la fábula.',
            'Quien guarda en verano tiene en invierno.',
        ],
    },
    'fantastico': {
        'pairs_prompt': 'Une cada autor o concepto con su descripción.',
        'pairs': [
            ('Lo fantástico', 'Irrupción de algo imposible en un mundo cotidiano.'),
            ('Suspenso', 'Tensión que mantiene al lector esperando qué pasará.'),
            ('Atmósfera', 'Ambiente emocional que envuelve la historia.'),
            ('Edgar Allan Poe', 'Autor estadounidense de «El corazón delator».'),
            ('Mary Shelley', 'Autora inglesa de «Frankenstein».'),
            ('Bram Stoker', 'Autor irlandés de «Drácula».'),
        ],
        'classify': {
            'prompt': '¿Qué atmósfera crea cada imagen?',
            'categories': ['Inquietante', 'Tranquila'],
            'items': [
                ('Una puerta que cruje en la oscuridad', 0),
                ('Pasos lentos en el desván vacío', 0),
                ('Un espejo que no refleja a quien lo mira', 0),
                ('El sol de la tarde entre los trigales', 1),
                ('Una taza de té junto a la chimenea', 1),
                ('Niños jugando en la plaza del pueblo', 1),
            ],
            'explanation': 'La atmósfera nace de las imágenes: sonidos y ausencias inquietan; la luz y lo cotidiano tranquilizan.',
        },
        'true_false': [
            ('Mary Shelley escribió «Frankenstein».', True),
            ('«Drácula» fue escrita por Edgar Allan Poe.', False),
            ('Bécquer escribió leyendas con elementos sobrenaturales.', True),
            ('El suspenso retrasa la información para crear tensión.', True),
            ('En lo fantástico, lo imposible aparece en un mundo que parece normal.', True),
            ('Horacio Quiroga fue un escritor chileno de novelas de caballerías.', False),
        ],
        'scramble': [
            ('misterio', 'Algo oculto que intriga'),
            ('espectro', 'Fantasma, aparición'),
            ('suspenso', 'Tensión por lo que vendrá'),
        ],
        'sentences': [
            'Lo imposible asomó por la puerta del desván.',
            'El miedo crece en el silencio de la espera.',
            'Una sombra se movió cuando nadie miraba.',
        ],
    },
    'aventuras': {
        'pairs_prompt': 'Une cada autor o personaje con su obra o descripción.',
        'pairs': [
            ('Julio Verne', '«Veinte mil leguas de viaje submarino»'),
            ('Robert Louis Stevenson', '«La isla del tesoro»'),
            ('Daniel Defoe', '«Robinson Crusoe»'),
            ('Jack London', '«La llamada de lo salvaje»'),
            ('Capitán Nemo', 'Comandante del submarino Nautilus.'),
            ('Phileas Fogg', 'Apostó que daría la vuelta al mundo en ochenta días.'),
        ],
        'classify': {
            'prompt': 'Clasifica cada novela: ¿es de Julio Verne o de otro autor?',
            'categories': ['Julio Verne', 'Otro autor'],
            'items': [
                ('Viaje al centro de la Tierra', 0),
                ('La vuelta al mundo en ochenta días', 0),
                ('Veinte mil leguas de viaje submarino', 0),
                ('La isla del tesoro', 1),
                ('Robinson Crusoe', 1),
                ('La llamada de lo salvaje', 1),
            ],
            'explanation': 'Verne escribió los tres primeros; «La isla del tesoro» es de Stevenson, «Robinson Crusoe» de Defoe y «La llamada de lo salvaje» de Jack London.',
        },
        'true_false': [
            ('Robinson Crusoe naufraga y vive en una isla.', True),
            ('Jim Hawkins es el joven protagonista de «La isla del tesoro».', True),
            ('El Nautilus es un globo aerostático.', False),
            ('Julio Verne era un escritor francés.', True),
            ('Viernes es el compañero de Robinson Crusoe en la isla.', True),
            ('Long John Silver es el capitán del Nautilus.', False),
        ],
        'scramble': [
            ('brújula', 'Instrumento que señala el norte'),
            ('tesoro', 'Riqueza escondida'),
            ('náufrago', 'Quien sobrevive a un naufragio'),
        ],
        'sentences': [
            'La aventura empieza donde termina el mapa.',
            'El capitán Nemo recorría los mares en el Nautilus.',
            'Todo viaje cambia a quien se atreve a hacerlo.',
        ],
    },
    'narrador': {
        'pairs_prompt': 'Une cada tipo de narrador con su descripción.',
        'pairs': [
            ('Narrador protagonista', 'Cuenta en primera persona su propia historia.'),
            ('Narrador testigo', 'Cuenta lo que vio, sin ser el protagonista.'),
            ('Narrador omnisciente', 'Lo sabe todo, incluso lo que piensan los personajes.'),
            ('Narrador objetivo', 'Cuenta solo lo que se ve, como una cámara.'),
            ('Primera persona', 'Se narra con «yo» o «nosotros».'),
            ('Tercera persona', 'Se narra con «él», «ella» o «ellos».'),
        ],
        'classify': {
            'prompt': '¿En qué persona está narrada cada frase?',
            'categories': ['Primera persona', 'Tercera persona'],
            'items': [
                ('Aquella mañana desperté antes que el sol.', 0),
                ('Nunca olvidaré la voz de mi abuela.', 0),
                ('Nosotros llegamos tarde al puerto.', 0),
                ('Marta abrió la carta con las manos temblorosas.', 1),
                ('El capitán sabía que nadie lo obedecería.', 1),
                ('Los viajeros se detuvieron junto al río.', 1),
            ],
            'explanation': 'La primera persona usa «yo» o «nosotros»; la tercera habla de «él», «ella» o «ellos».',
        },
        'true_false': [
            ('El narrador omnisciente conoce los pensamientos de los personajes.', True),
            ('El narrador testigo es siempre el protagonista.', False),
            ('En primera persona se usa el pronombre «yo».', True),
            ('El narrador y el autor son siempre la misma persona.', False),
            ('El narrador objetivo cuenta solo lo que puede observarse.', True),
            ('El doctor Watson narra muchas aventuras de Sherlock Holmes.', True),
        ],
        'scramble': [
            ('narrador', 'Voz que cuenta la historia'),
            ('testigo', 'Quien vio los hechos'),
            ('omnisciente', 'Que lo sabe todo'),
        ],
        'sentences': [
            'El narrador elige qué mirar y qué callar.',
            'Quien cuenta la historia también la transforma.',
            'Un testigo solo sabe lo que alcanzó a ver.',
        ],
    },
    'tiempo': {
        'pairs_prompt': 'Une cada recurso temporal o espacial con su definición.',
        'pairs': [
            ('Analepsis', 'Salto al pasado dentro de la narración.'),
            ('Prolepsis', 'Adelanto de algo que ocurrirá más tarde.'),
            ('Tiempo lineal', 'Los hechos se cuentan en el orden en que ocurren.'),
            ('In medias res', 'Comenzar el relato en mitad de la acción.'),
            ('Ambiente', 'Lugar y atmósfera donde transcurre la historia.'),
            ('Elipsis', 'Omitir un período de tiempo en el relato.'),
        ],
        'classify': {
            'prompt': '¿Cada expresión indica un lugar o un momento?',
            'categories': ['Espacio', 'Tiempo'],
            'items': [
                ('En una aldea junto al mar', 0), ('Bajo el puente de piedra', 0), ('En el desván de la casa', 0),
                ('Veinte años después', 1), ('Aquella noche de invierno', 1), ('Al amanecer', 1),
            ],
            'explanation': 'Las marcas de espacio sitúan dónde ocurre la historia; las de tiempo, cuándo.',
        },
        'true_false': [
            ('Una analepsis cuenta hechos del pasado.', True),
            ('Comenzar «in medias res» es empezar por el final.', False),
            ('La elipsis omite un período de tiempo.', True),
            ('El ambiente puede reflejar las emociones de los personajes.', True),
            ('En el tiempo lineal los hechos aparecen desordenados.', False),
            ('«La Odisea» comienza cuando Ulises lleva años lejos de su hogar.', True),
        ],
        'scramble': [
            ('elipsis', 'Salto que omite tiempo'),
            ('ambiente', 'Lugar y atmósfera del relato'),
            ('pasado', 'Tiempo que ya ocurrió'),
        ],
        'sentences': [
            'Veinte años después, volvió a la casa de su infancia.',
            'El relato saltó al pasado como quien abre un baúl.',
            'El lugar también cuenta la historia.',
        ],
    },
    'argumentacion': {
        'pairs_prompt': 'Une cada término de la argumentación con su definición.',
        'pairs': [
            ('Tesis', 'Idea principal que el autor defiende.'),
            ('Argumento', 'Razón que apoya la tesis.'),
            ('Contraargumento', 'Razón que se opone a la tesis.'),
            ('Falacia', 'Razonamiento que parece válido pero no lo es.'),
            ('Reseña', 'Texto que describe y valora una obra.'),
            ('Conclusión', 'Cierre que resume y refuerza la postura.'),
        ],
        'classify': {
            'prompt': '¿Es un argumento razonable o una falacia?',
            'categories': ['Argumento razonable', 'Falacia'],
            'items': [
                ('Leer a diario amplía el vocabulario, porque nos expone a palabras nuevas.', 0),
                ('La novela tiene mil páginas, así que no se lee en una tarde.', 0),
                ('Practicar la lectura en voz alta mejora la fluidez.', 0),
                ('Todos leen ese libro, así que debe ser bueno.', 1),
                ('No le creas: ni siquiera sabe vestirse.', 1),
                ('Si lees un cómic, nunca leerás un clásico.', 1),
            ],
            'explanation': 'Un buen argumento da razones relacionadas con la idea; la falacia apela a la mayoría, ataca a la persona o exagera consecuencias.',
        },
        'true_false': [
            ('La tesis es la opinión que el autor defiende.', True),
            ('Atacar a la persona en vez de a su idea es una falacia.', True),
            ('Un argumento debe apoyar la tesis con razones.', True),
            ('Una reseña solo resume la obra, sin valorarla.', False),
            ('«Todos lo hacen, así que está bien» es un buen argumento.', False),
            ('El contraargumento presenta una postura opuesta.', True),
        ],
        'scramble': [
            ('tesis', 'Idea que se defiende'),
            ('falacia', 'Razonamiento engañoso'),
            ('reseña', 'Texto que valora una obra'),
        ],
        'sentences': [
            'Una buena tesis se defiende con buenas razones.',
            'Discutir ideas no es atacar personas.',
            'La reseña cuenta de qué trata una obra y cuánto vale.',
        ],
    },
    'epocas': {
        'pairs_prompt': 'Une cada época o movimiento con su descripción.',
        'pairs': [
            ('Siglo de Oro', 'Esplendor de las letras españolas en los siglos XVI y XVII.'),
            ('Romanticismo', 'Movimiento del siglo XIX que exalta el sentimiento y la libertad.'),
            ('Realismo', 'Retrata la sociedad de forma fiel y detallada.'),
            ('Modernismo', 'Movimiento encabezado por Rubén Darío, amante de la belleza y la musicalidad.'),
            ('Renacimiento', 'Época que recupera los modelos de la Antigüedad clásica.'),
            ('Barroco', 'Estilo del siglo XVII, complejo, ingenioso y lleno de contrastes.'),
        ],
        'classify': {
            'prompt': 'Clasifica a cada autor según su época.',
            'categories': ['Siglo de Oro', 'Romanticismo', 'Realismo'],
            'items': [
                ('Miguel de Cervantes', 0), ('Lope de Vega', 0),
                ('Gustavo Adolfo Bécquer', 1), ('José de Espronceda', 1),
                ('Benito Pérez Galdós', 2), ('Leopoldo Alas, «Clarín»', 2),
            ],
            'explanation': 'Cervantes y Lope pertenecen al Siglo de Oro; Bécquer y Espronceda, al Romanticismo; Galdós y Clarín, al Realismo.',
        },
        'true_false': [
            ('Cervantes y Lope de Vega pertenecen al Siglo de Oro.', True),
            ('Bécquer es un autor del Romanticismo.', True),
            ('El Realismo prefiere mundos fantásticos e imposibles.', False),
            ('Rubén Darío es la gran figura del Modernismo.', True),
            ('«La Regenta» es una novela de Leopoldo Alas, «Clarín».', True),
            ('El Romanticismo desprecia los sentimientos y la naturaleza.', False),
        ],
        'scramble': [
            ('barroco', 'Estilo del siglo XVII lleno de contrastes'),
            ('realismo', 'Movimiento que retrata la sociedad'),
            ('romántico', 'Que exalta el sentimiento'),
        ],
        'sentences': [
            'Cada época mira el mundo con sus propios ojos.',
            'El Romanticismo puso el corazón en el centro.',
            'El Realismo llevó la calle a la novela.',
        ],
    },
    'autores': {
        'pairs_prompt': 'Une cada autor con una de sus obras.',
        'pairs': [
            ('Miguel de Cervantes', '«Don Quijote de la Mancha»'),
            ('Gabriela Mistral', '«Desolación»'),
            ('Pablo Neruda', '«Veinte poemas de amor y una canción desesperada»'),
            ('Gustavo Adolfo Bécquer', '«Rimas»'),
            ('William Shakespeare', '«Hamlet»'),
            ('Dante Alighieri', '«La Divina Comedia»'),
        ],
        'classify': {
            'prompt': 'Clasifica a cada autor según su país de nacimiento.',
            'categories': ['Chile', 'España'],
            'items': [
                ('Gabriela Mistral', 0), ('Pablo Neruda', 0), ('Vicente Huidobro', 0),
                ('Miguel de Cervantes', 1), ('Federico García Lorca', 1), ('Benito Pérez Galdós', 1),
            ],
            'explanation': 'Mistral, Neruda y Huidobro nacieron en Chile; Cervantes, García Lorca y Pérez Galdós, en España.',
        },
        'true_false': [
            ('Gabriela Mistral fue la primera persona latinoamericana en recibir el Premio Nobel de Literatura.', True),
            ('Pablo Neruda recibió el Premio Nobel de Literatura en 1971.', True),
            ('Cervantes escribió «Hamlet».', False),
            ('La tradición atribuye a Homero «La Ilíada» y «La Odisea».', True),
            ('Dante Alighieri escribió «La Divina Comedia».', True),
            ('Rubén Darío nació en Chile.', False),
        ],
        'scramble': [
            ('quijote', 'Hidalgo de La Mancha'),
            ('neruda', 'Poeta chileno, Nobel en 1971'),
            ('mistral', 'Poeta chilena, Nobel en 1945'),
        ],
        'sentences': [
            'Gabriela Mistral recibió el Nobel de Literatura en 1945.',
            'Don Quijote salió a los caminos con Sancho Panza.',
            'Los grandes autores siguen hablándonos siglos después.',
        ],
    },
    'maestria': {
        'pairs_prompt': 'Repaso general: une cada concepto con su definición.',
        'pairs': [
            ('Metáfora', 'Identifica una cosa con otra sin usar «como».'),
            ('Analepsis', 'Salto al pasado dentro del relato.'),
            ('Moraleja', 'Enseñanza final de una fábula.'),
            ('Soneto', 'Poema de catorce versos.'),
            ('Tesis', 'Idea que el autor defiende.'),
            ('Acotación', 'Indicación escénica del autor teatral.'),
        ],
        'classify': {
            'prompt': 'Clasifica cada obra según su género.',
            'categories': ['Narrativo', 'Lírico', 'Dramático'],
            'items': [
                ('Don Quijote de la Mancha', 0), ('La isla del tesoro', 0),
                ('Rimas, de Bécquer', 1), ('Veinte poemas de amor y una canción desesperada', 1),
                ('Romeo y Julieta', 2), ('La vida es sueño', 2),
            ],
            'explanation': 'El Quijote y «La isla del tesoro» son novelas; las «Rimas» y los «Veinte poemas», poesía lírica; «Romeo y Julieta» y «La vida es sueño», teatro.',
        },
        'true_false': [
            ('La hipérbole es una exageración.', True),
            ('El narrador testigo conoce los pensamientos de todos los personajes.', False),
            ('Una leyenda suele estar ligada a un lugar concreto.', True),
            ('La prolepsis adelanta hechos futuros.', True),
            ('El Siglo de Oro español ocurrió en el siglo XX.', False),
            ('Las fábulas terminan a menudo con una moraleja.', True),
        ],
        'scramble': [
            ('lector', 'Quien da vida a un libro al leerlo'),
            ('biblioteca', 'Casa de los libros'),
            ('literatura', 'Arte de la palabra'),
        ],
        'sentences': [
            'Leer es viajar sin moverse de la silla.',
            'Cada libro terminado abre la puerta de otro.',
            'El lector completa lo que el autor deja abierto.',
        ],
    },
}
