"""
Bancos de juegos de las unidades 21 a 30 (mismo formato que banks.py).
Los datos sobre autores, obras y fechas están verificados.
"""

BANKS_2 = {
    'medios': {
        'pairs_prompt': 'Une cada concepto periodístico con su definición.',
        'pairs': [
            ('Noticia', 'Texto que informa de un hecho reciente y de interés público.'),
            ('Pirámide invertida', 'Estructura que pone lo más importante al comienzo.'),
            ('Lead', 'Primer párrafo de la noticia, que responde qué, quién, cuándo y dónde.'),
            ('Crónica', 'Relato de hechos en orden temporal con la mirada personal de quien escribe.'),
            ('Reportaje', 'Texto que investiga un tema en profundidad con datos y testimonios.'),
            ('Entrevista', 'Conversación de preguntas y respuestas con una persona.'),
        ],
        'classify': {
            'prompt': 'Clasifica cada género periodístico: ¿informa o da una opinión?',
            'categories': ['Informativo', 'De opinión'],
            'items': [
                ('Noticia', 0), ('Reportaje', 0), ('Entrevista', 0),
                ('Editorial', 1), ('Columna de opinión', 1), ('Carta al director', 1),
            ],
            'explanation': 'La noticia, el reportaje y la entrevista informan; el editorial, la columna y la carta al director expresan opiniones.',
        },
        'true_false': [
            ('La pirámide invertida pone los datos más importantes al principio.', True),
            ('Un editorial expresa la opinión del medio de comunicación.', True),
            ('Una noticia debe incluir la opinión personal del periodista.', False),
            ('El titular resume el hecho principal en pocas palabras.', True),
            ('Una crónica nunca sigue un orden temporal.', False),
            ('Contrastar fuentes ayuda a detectar noticias falsas.', True),
            ('Una noticia falsa siempre es fácil de reconocer.', False),
        ],
        'scramble': [
            ('noticia', 'Texto que informa de un hecho reciente'),
            ('titular', 'Frase que encabeza una noticia'),
            ('crónica', 'Relato de hechos con la mirada de quien escribe'),
        ],
        'sentences': [
            'Una buena noticia responde qué, quién, cuándo y dónde.',
            'Antes de compartir una noticia, revisa su fuente.',
            'El titular invita a leer el resto del texto.',
        ],
    },
    'policial': {
        'pairs_prompt': 'Une cada concepto del relato policial con su definición.',
        'pairs': [
            ('Detective', 'Personaje que investiga y resuelve el enigma.'),
            ('Coartada', 'Prueba de que un sospechoso estaba en otro lugar.'),
            ('Pista', 'Indicio que ayuda a resolver el caso.'),
            ('Sospechoso', 'Persona a la que se cree posible culpable.'),
            ('Enigma', 'Misterio que plantea el relato.'),
            ('Deducción', 'Conclusión lógica a partir de los indicios.'),
        ],
        'classify': {
            'prompt': 'Clasifica cada personaje u obra según su autor.',
            'categories': ['Edgar Allan Poe', 'Arthur Conan Doyle', 'Agatha Christie'],
            'items': [
                ('C. Auguste Dupin', 0), ('«Los crímenes de la calle Morgue»', 0),
                ('Sherlock Holmes', 1), ('El doctor Watson', 1),
                ('Hércules Poirot', 2), ('Miss Marple', 2),
            ],
            'explanation': 'Dupin es de Poe; Holmes y Watson, de Conan Doyle; Poirot y Miss Marple, de Agatha Christie.',
        },
        'true_false': [
            ('«Los crímenes de la calle Morgue», de Poe, se considera uno de los primeros relatos policiales.', True),
            ('Sherlock Holmes vive en el 221B de Baker Street.', True),
            ('Hércules Poirot es un detective creado por Arthur Conan Doyle.', False),
            ('En el relato policial clásico, el lector recibe pistas para intentar resolver el caso.', True),
            ('Una coartada demuestra que el sospechoso estuvo en el lugar del crimen.', False),
            ('El detective clásico resuelve el caso por suerte, sin razonar.', False),
        ],
        'scramble': [
            ('coartada', 'Prueba de que alguien estaba en otro lugar'),
            ('detective', 'Quien investiga el caso'),
            ('sospechoso', 'Posible culpable'),
        ],
        'sentences': [
            'Cada detalle de la escena puede ser una pista.',
            'El detective ordena los indicios hasta encontrar la verdad.',
            'Una coartada falsa siempre deja una grieta.',
        ],
    },
    'ciencia_ficcion': {
        'pairs_prompt': 'Une cada concepto de la ciencia ficción con su definición.',
        'pairs': [
            ('Ciencia ficción', 'Género que imagina cómo la ciencia y la técnica cambian el mundo.'),
            ('Utopía', 'Sociedad ideal imaginada, sin los males del presente.'),
            ('Distopía', 'Sociedad imaginada en la que todo salió mal, como advertencia.'),
            ('Robot', 'Máquina capaz de realizar tareas por sí misma.'),
            ('Androide', 'Robot con apariencia humana.'),
            ('Viaje en el tiempo', 'Desplazamiento hacia el pasado o el futuro.'),
        ],
        'classify': {
            'prompt': 'Clasifica cada obra según su autor.',
            'categories': ['Julio Verne', 'H. G. Wells', 'Ray Bradbury'],
            'items': [
                ('«Veinte mil leguas de viaje submarino»', 0), ('«De la Tierra a la Luna»', 0),
                ('«La máquina del tiempo»', 1), ('«La guerra de los mundos»', 1),
                ('«Fahrenheit 451»', 2), ('«Crónicas marcianas»', 2),
            ],
            'explanation': 'Verne escribió los viajes submarino y lunar; Wells, «La máquina del tiempo» y «La guerra de los mundos»; Bradbury, «Fahrenheit 451» y «Crónicas marcianas».',
        },
        'true_false': [
            ('Isaac Asimov formuló las Tres Leyes de la Robótica.', True),
            ('La palabra «robot» se popularizó con la obra teatral «R.U.R.», de Karel Čapek.', True),
            ('Una distopía presenta una sociedad perfecta y feliz.', False),
            ('En «Fahrenheit 451», los bomberos queman libros.', True),
            ('Julio Verne escribió «La máquina del tiempo».', False),
            ('La ciencia ficción solo habla del futuro y nunca del presente.', False),
        ],
        'scramble': [
            ('robot', 'Máquina que hace tareas por sí misma'),
            ('distopía', 'Sociedad imaginada que salió mal'),
            ('androide', 'Robot con forma humana'),
        ],
        'sentences': [
            'La ciencia ficción se pregunta qué pasaría si.',
            'Un robot no debe dañar a un ser humano.',
            'Las distopías nos advierten sobre el presente.',
        ],
    },
    'humor': {
        'pairs_prompt': 'Une cada recurso del humor con su definición.',
        'pairs': [
            ('Ironía', 'Decir lo contrario de lo que se quiere dar a entender.'),
            ('Sátira', 'Burla que critica defectos de personas o de la sociedad.'),
            ('Parodia', 'Imitación burlesca de una obra o de un estilo.'),
            ('Caricatura', 'Retrato que exagera rasgos para hacer reír.'),
            ('Juego de palabras', 'Uso ingenioso de los dobles sentidos de las palabras.'),
            ('Humor absurdo', 'Comicidad basada en situaciones ilógicas.'),
        ],
        'classify': {
            'prompt': 'Clasifica cada frase según el recurso de humor que usa.',
            'categories': ['Ironía', 'Hipérbole', 'Juego de palabras'],
            'items': [
                ('«¡Qué día tan lindo!», dijo empapado bajo la tormenta.', 0),
                ('«Excelente idea», murmuró al ver la cocina llena de humo.', 0),
                ('Tenía tanta hambre que se habría comido un elefante.', 1),
                ('Esperé mil años en la fila del banco.', 1),
                ('—¿Qué le dijo un techo a otro? —Techo de menos.', 2),
                ('—¿Cuál es el colmo de un jardinero? —Que su novia lo deje plantado.', 2),
            ],
            'explanation': 'La ironía dice lo contrario de lo que piensa; la hipérbole exagera; el juego de palabras aprovecha los dobles sentidos («techo» y «te echo», «plantado»).',
        },
        'true_false': [
            ('La parodia imita una obra para producir un efecto cómico.', True),
            ('El Quijote nació en parte como parodia de los libros de caballerías.', True),
            ('La ironía siempre dice exactamente lo que piensa el hablante.', False),
            ('La sátira puede servir para criticar a la sociedad.', True),
            ('Un texto con humor no puede tratar temas serios.', False),
            ('Francisco de Quevedo es conocido por sus textos satíricos.', True),
            ('La caricatura disimula los rasgos de una persona hasta hacerlos invisibles.', False),
        ],
        'scramble': [
            ('ironía', 'Decir lo contrario de lo que se piensa'),
            ('parodia', 'Imitación que hace reír'),
            ('sátira', 'Burla que critica'),
        ],
        'sentences': [
            'El humor también puede decir verdades incómodas.',
            'La ironía se entiende gracias al contexto.',
            'Reírse de uno mismo es todo un arte.',
        ],
    },
    'boom': {
        'pairs_prompt': 'Une cada concepto del Boom con su definición.',
        'pairs': [
            ('Realismo mágico', 'Presenta lo maravilloso como algo natural y cotidiano.'),
            ('Boom latinoamericano', 'Auge internacional de la novela latinoamericana en los años sesenta y setenta.'),
            ('Macondo', 'Pueblo imaginario creado por Gabriel García Márquez.'),
            ('Comala', 'Pueblo de «Pedro Páramo» donde murmuran los muertos.'),
            ('Lo real maravilloso', 'Idea de Alejo Carpentier sobre lo asombroso de la realidad americana.'),
            ('Rayuela', 'Novela de Julio Cortázar que puede leerse en más de un orden.'),
        ],
        'classify': {
            'prompt': 'Clasifica cada obra según su autor.',
            'categories': ['Gabriel García Márquez', 'Julio Cortázar', 'Mario Vargas Llosa'],
            'items': [
                ('«Cien años de soledad»', 0), ('«Crónica de una muerte anunciada»', 0),
                ('«Rayuela»', 1), ('«Historias de cronopios y de famas»', 1),
                ('«La ciudad y los perros»', 2), ('«La casa verde»', 2),
            ],
            'explanation': 'Las dos primeras son de García Márquez; «Rayuela» y los cronopios, de Cortázar; «La ciudad y los perros» y «La casa verde», de Vargas Llosa.',
        },
        'true_false': [
            ('Gabriel García Márquez recibió el Premio Nobel de Literatura en 1982.', True),
            ('Mario Vargas Llosa recibió el Premio Nobel de Literatura en 2010.', True),
            ('«Cien años de soledad» se publicó en 1967.', True),
            ('Macondo es una ciudad que aparece en los mapas de Colombia.', False),
            ('Julio Cortázar nació en Chile.', False),
            ('En el realismo mágico, los personajes se asombran a cada rato de lo extraordinario.', False),
        ],
        'scramble': [
            ('macondo', 'Pueblo imaginario de García Márquez'),
            ('rayuela', 'Novela de Cortázar y juego de niños'),
            ('comala', 'Pueblo de «Pedro Páramo»'),
        ],
        'sentences': [
            'En Macondo lo extraordinario parecía cosa de todos los días.',
            'El Boom llevó la novela latinoamericana a todo el mundo.',
            'Rayuela se puede leer saltando de capítulo en capítulo.',
        ],
    },
    'autobiografia': {
        'pairs_prompt': 'Une cada forma de escritura íntima con su definición.',
        'pairs': [
            ('Diario íntimo', 'Registro personal, con fecha, de lo vivido y lo sentido.'),
            ('Carta', 'Texto dirigido a un destinatario, con saludo y despedida.'),
            ('Autobiografía', 'Relato de la propia vida escrito por su protagonista.'),
            ('Biografía', 'Relato de la vida de una persona escrito por otra.'),
            ('Memorias', 'Recuerdos de una vida escritos años después, mirando hacia atrás.'),
            ('Novela epistolar', 'Novela escrita en forma de cartas.'),
        ],
        'classify': {
            'prompt': 'Clasifica cada texto: ¿lo escribe la misma persona que lo vivió?',
            'categories': ['Autobiográfico', 'Biográfico'],
            'items': [
                ('El diario de Ana Frank', 0),
                ('«Confieso que he vivido», de Pablo Neruda', 0),
                ('Un diario de viaje escrito por su viajera', 0),
                ('Una enciclopedia que narra la vida de Cervantes', 1),
                ('Un libro de un historiador sobre la vida de Napoleón', 1),
                ('Un reportaje sobre la vida de Gabriela Mistral', 1),
            ],
            'explanation': 'En lo autobiográfico, quien escribe es quien vivió los hechos; en lo biográfico, otra persona cuenta esa vida.',
        },
        'true_false': [
            ('Ana Frank escribió su diario mientras vivía escondida en Ámsterdam.', True),
            ('«Confieso que he vivido» son las memorias de Pablo Neruda.', True),
            ('Una biografía la escribe siempre la misma persona cuya vida se cuenta.', False),
            ('«Drácula», de Bram Stoker, se cuenta en gran parte con cartas y diarios.', True),
            ('Un diario íntimo se escribe pensando en publicarlo en el periódico.', False),
            ('Las cartas nunca llevan saludo ni despedida.', False),
        ],
        'scramble': [
            ('diario', 'Cuaderno donde se anota lo vivido cada día'),
            ('memorias', 'Recuerdos de una vida'),
            ('carta', 'Mensaje escrito para alguien'),
        ],
        'sentences': [
            'Ana Frank llamaba Kitty a su diario.',
            'Una carta guarda la voz de quien la escribió.',
            'Escribir la propia vida es volver a vivirla.',
        ],
    },
    'comic': {
        'pairs_prompt': 'Une cada elemento de la historieta con su definición.',
        'pairs': [
            ('Viñeta', 'Recuadro que muestra un instante de la historieta.'),
            ('Globo', 'Espacio que encierra lo que dicen o piensan los personajes.'),
            ('Cartela', 'Recuadro con la voz del narrador.'),
            ('Onomatopeya', 'Palabra que imita un sonido, como «¡pum!».'),
            ('Calle', 'Espacio en blanco entre una viñeta y otra.'),
            ('Novela gráfica', 'Historieta extensa y unitaria, de temas a menudo complejos.'),
        ],
        'classify': {
            'prompt': 'Clasifica cada personaje de historieta según su país de origen.',
            'categories': ['Chile', 'Argentina', 'Otros países'],
            'items': [
                ('Condorito', 0), ('Mampato', 0),
                ('Mafalda', 1), ('El Eternauta', 1),
                ('Tintín', 2), ('Astérix', 2),
            ],
            'explanation': 'Condorito y Mampato son chilenos; Mafalda y El Eternauta, argentinos; Tintín es belga y Astérix, francés.',
        },
        'true_false': [
            ('Mafalda fue creada por el dibujante argentino Quino.', True),
            ('Condorito fue creado por el chileno Pepo.', True),
            ('«Maus», de Art Spiegelman, recibió un premio Pulitzer especial.', True),
            ('En una historieta, la cartela contiene el diálogo de los personajes.', False),
            ('Las onomatopeyas imitan sonidos.', True),
            ('Una novela gráfica no puede tratar temas históricos.', False),
            ('En nuestra lengua, las viñetas se leen de derecha a izquierda.', False),
        ],
        'scramble': [
            ('viñeta', 'Recuadro de una historieta'),
            ('globo', 'Donde van las palabras de los personajes'),
            ('mafalda', 'Niña creada por Quino'),
        ],
        'sentences': [
            'Cada viñeta guarda un instante de la historia.',
            'En el cómic, la imagen y la palabra cuentan juntas.',
            'Mafalda odiaba la sopa.',
        ],
    },
    'sociedad': {
        'pairs_prompt': 'Une cada concepto con su definición.',
        'pairs': [
            ('Contexto de producción', 'Momento histórico, social y cultural en que se escribe una obra.'),
            ('Contexto de recepción', 'Momento en que un lector lee e interpreta la obra.'),
            ('Crítica social', 'Denuncia de las injusticias de una sociedad.'),
            ('Naturalismo', 'Corriente que muestra cómo el medio y la herencia marcan a las personas.'),
            ('Costumbrismo', 'Retrato de las costumbres de un lugar y de su gente.'),
            ('Literatura comprometida', 'Obra que toma posición frente a los problemas de su tiempo.'),
        ],
        'classify': {
            'prompt': 'Clasifica cada obra según el problema social que muestra.',
            'categories': ['Trabajo y pobreza', 'Esclavitud y racismo'],
            'items': [
                ('«Sub terra», de Baldomero Lillo', 0),
                ('«Oliver Twist», de Charles Dickens', 0),
                ('«Las uvas de la ira», de John Steinbeck', 0),
                ('«La cabaña del tío Tom», de Harriet Beecher Stowe', 1),
                ('«Matar a un ruiseñor», de Harper Lee', 1),
                ('«Raíces», de Alex Haley', 1),
            ],
            'explanation': 'Lillo, Dickens y Steinbeck retratan el trabajo duro y la pobreza; Stowe, Lee y Haley denuncian la esclavitud y el racismo.',
        },
        'true_false': [
            ('Baldomero Lillo retrató la vida de los mineros del carbón en «Sub terra».', True),
            ('Charles Dickens denunció la pobreza infantil de la Inglaterra del siglo XIX.', True),
            ('El contexto de producción no influye en nada en una obra.', False),
            ('«La cabaña del tío Tom» trata sobre la esclavitud en Estados Unidos.', True),
            ('La literatura nunca ha logrado cambiar la opinión de sus lectores.', False),
            ('Una misma obra puede leerse de forma distinta en otra época.', True),
            ('El costumbrismo evita describir las costumbres de un lugar.', False),
        ],
        'scramble': [
            ('contexto', 'Circunstancias en que nace una obra'),
            ('denuncia', 'Acusación pública de una injusticia'),
            ('minero', 'Trabajador de la mina'),
        ],
        'sentences': [
            'Toda obra nace en un tiempo y un lugar.',
            'Baldomero Lillo escribió sobre los mineros de Lota.',
            'Conocer el contexto ayuda a entender la obra.',
        ],
    },
    'escritura': {
        'pairs_prompt': 'Une cada etapa o concepto de la escritura con su definición.',
        'pairs': [
            ('Planificación', 'Etapa en que se definen propósito, destinatario e ideas.'),
            ('Borrador', 'Primera versión de un texto, que se puede corregir.'),
            ('Coherencia', 'Las ideas se refieren a un mismo tema y avanzan con lógica.'),
            ('Cohesión', 'Conectores y referencias que unen las oraciones.'),
            ('Conector', 'Palabra que enlaza ideas, como «sin embargo» o «por lo tanto».'),
            ('Edición', 'Revisión final de ortografía, puntuación y presentación.'),
        ],
        'classify': {
            'prompt': 'Clasifica cada conector según la relación que expresa.',
            'categories': ['Adición', 'Contraste', 'Consecuencia'],
            'items': [
                ('además', 0), ('también', 0),
                ('sin embargo', 1), ('pero', 1),
                ('por lo tanto', 2), ('por eso', 2),
            ],
            'explanation': '«Además» y «también» suman ideas; «sin embargo» y «pero» las oponen; «por lo tanto» y «por eso» presentan una consecuencia.',
        },
        'true_false': [
            ('Un borrador es la versión definitiva de un texto.', False),
            ('«Sin embargo» es un conector de contraste.', True),
            ('Revisar un texto incluye comprobar que las ideas sigan un orden lógico.', True),
            ('Repetir la misma palabra muchas veces mejora la cohesión.', False),
            ('Antes de escribir conviene pensar en quién leerá el texto.', True),
            ('La ortografía no importa en la edición final.', False),
        ],
        'scramble': [
            ('borrador', 'Primera versión de un texto'),
            ('conector', 'Palabra que une ideas'),
            ('coherencia', 'Unidad de sentido de un texto'),
        ],
        'sentences': [
            'Escribir es reescribir hasta que el texto respire.',
            'Un buen conector une dos ideas sin esfuerzo.',
            'Primero planifica, luego escribe y al final revisa.',
        ],
    },
    'cumbre': {
        'pairs_prompt': 'Repaso de la cumbre: une cada concepto con su definición.',
        'pairs': [
            ('Pirámide invertida', 'Estructura de la noticia que empieza por lo más importante.'),
            ('Coartada', 'Prueba de que un sospechoso estaba en otro lugar.'),
            ('Distopía', 'Sociedad imaginada que salió mal, como advertencia.'),
            ('Parodia', 'Imitación burlesca de una obra o de un estilo.'),
            ('Realismo mágico', 'Lo maravilloso contado como algo cotidiano.'),
            ('Viñeta', 'Recuadro que muestra un instante de la historieta.'),
        ],
        'classify': {
            'prompt': 'Clasifica cada texto según su propósito principal.',
            'categories': ['Informar', 'Opinar', 'Contar una historia'],
            'items': [
                ('Una noticia sobre un terremoto', 0), ('Un reportaje sobre el agua en el norte', 0),
                ('Un editorial sobre la educación', 1), ('Una columna que critica un estreno', 1),
                ('Un cuento policial', 2), ('Una novela gráfica', 2),
            ],
            'explanation': 'Noticia y reportaje informan; editorial y columna opinan; el cuento y la novela gráfica cuentan historias.',
        },
        'true_false': [
            ('Una autobiografía la escribe el propio protagonista.', True),
            ('Hércules Poirot es un detective creado por Agatha Christie.', True),
            ('En la pirámide invertida, lo más importante va al final.', False),
            ('La sátira usa el humor para criticar.', True),
            ('«Fahrenheit 451» fue escrita por Julio Verne.', False),
            ('Un texto es coherente cuando sus ideas se refieren a un mismo tema.', True),
            ('Gabriel García Márquez nació en Argentina.', False),
        ],
        'scramble': [
            ('cumbre', 'Punto más alto de una montaña'),
            ('maestro', 'Quien domina un arte'),
            ('curiosidad', 'Deseo de saber más'),
        ],
        'sentences': [
            'Cada página leída fue un paso hacia la cumbre.',
            'Un gran lector nunca deja de hacerse preguntas.',
            'Desde la cumbre se ven todos los caminos recorridos.',
        ],
    },
}
