# Generated by Django 6.0.4 on 2026-09-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.PositiveIntegerField(default=1, help_text='Nivel actual del lector.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak_current',
            field=models.PositiveIntegerField(default=0, help_text='Racha actual de días consecutivos leyendo.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak_last_date',
            field=models.DateField(blank=True, help_text='Último día en el que se validó la racha de lectura.', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='xp',
            field=models.PositiveIntegerField(default=0, help_text='Puntos de experiencia acumulados.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ink_balance',
            field=models.PositiveIntegerField(default=50, help_text='Tokens de energía (Tinta) disponibles para chatear con personajes de IA o adquirir contenido.'),
        ),
    ]
