# Generated by Django 6.0.4 on 2026-09-19 00:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_level_profile_streak_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='equipped_frame',
            field=models.CharField(blank=True, default='', help_text='Identificador del marco de perfil equipado.', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='equipped_title',
            field=models.CharField(blank=True, default='', help_text='Título literario honorífico equipado.', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='hearts',
            field=models.PositiveSmallIntegerField(default=5, help_text='Vidas actuales para ejercicios de comprensión (0 a 5).'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hearts_last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Último timestamp en el que se sincronizaron las vidas.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak_max',
            field=models.PositiveIntegerField(default=0, help_text='Mejor racha histórica de días consecutivos.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak_shields',
            field=models.PositiveSmallIntegerField(default=0, help_text='Escudos protectores de racha activos (máximo 2 almacenables).'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='streak_current',
            field=models.PositiveIntegerField(default=0, help_text='Racha actual de días consecutivos leyendo o practicando.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='streak_last_date',
            field=models.DateField(blank=True, help_text='Último día en el que se validó la racha.', null=True),
        ),
    ]
