# Generated by Django 6.0.4 on 2026-10-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_book_editorial_notes_book_submission_declaration_and_more'),
        ('users', '0007_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, help_text='Géneros literarios seleccionados durante el onboarding o en perfil.', related_name='favorited_by_profiles', to='catalog.genre'),
        ),
        migrations.AddField(
            model_name='profile',
            name='followed_authors',
            field=models.ManyToManyField(blank=True, help_text='Autores literarios que el usuario sigue para recibir novedades.', related_name='followed_by_profiles', to='catalog.author'),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_completed_onboarding',
            field=models.BooleanField(default=False, help_text='Indica si el usuario completó la configuración inicial de rol y gustos literarios.'),
        ),
    ]
