# Generated by Django 6.0.4 on 2026-10-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_friend_code_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del usuario. Requerido para acceder a contenido restringido por edad.', null=True),
        ),
    ]
