# Generated by Django 6.0.4 on 2026-10-10 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetChallenge',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='password_reset_challenge', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=254)),
                ('nonce', models.CharField(max_length=64)),
                ('code_digest', models.CharField(blank=True, max_length=64)),
                ('password_fingerprint', models.CharField(max_length=64)),
                ('sent_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('request_window_start', models.DateTimeField()),
                ('request_count', models.PositiveSmallIntegerField(default=1)),
                ('reset_token_digest', models.CharField(blank=True, default='', max_length=64)),
                ('verified_expires_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
