# Generated by Django 6.0.4 on 2026-09-30 23:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_rename_finance_tra_buy_ord_idx_finance_tra_buy_ord_4f39a9_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalWebhook',
            fields=[
                ('event_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('code', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('daily_token_limit', models.PositiveIntegerField()),
                ('daily_time_limit', models.PositiveIntegerField(blank=True, help_text='Segundos; NULL = sin límite horario', null=True)),
                ('monthly_ink_bonus', models.PositiveIntegerField(default=0)),
                ('benefits', models.JSONField(default=list)),
                ('provider_plan_id', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='CLP', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider',
            field=models.CharField(default='webpay', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='item_type',
            field=models.CharField(choices=[('book', 'Libro'), ('ink', 'Tinta'), ('plan', 'Suscripción')], max_length=10),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='APPROVAL_PENDING', max_length=30)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('paid_until', models.DateTimeField(blank=True, null=True)),
                ('renews_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('previous_frame', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pending_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.subscriptionplan')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
