# Generated by Django 6.0.4 on 2026-09-30 23:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_seed_subscription_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='creation_request_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.CreateModel(
            name='PayPalSubscriptionBinding',
            fields=[
                ('provider_subscription_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.subscriptionplan')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.usersubscription')),
            ],
        ),
    ]
