# Generated by Django 6.0.4 on 2026-09-30 23:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_usersubscription_creation_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalsubscriptionbinding',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
