# Generated by Django 6.0.4 on 2026-08-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_genre_cover_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_published', 'is_featured'], name='catalog_boo_is_publ_5fcf8b_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['status'], name='catalog_boo_status_b30b19_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['book', 'order'], name='catalog_cha_book_id_a725ce_idx'),
        ),
    ]
