# Generated by Django 6.0.4 on 2026-09-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_genre_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.PositiveIntegerField(default=0, help_text='Número estimado de páginas.'),
        ),
    ]
