# Generated by Django 6.0.4 on 2026-09-29 14:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_book_word_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookVocabulary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal. Ver documentación de diseño para justificación.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación. Inmutable post-creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación. Gestionado automáticamente.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indica un registro borrado lógicamente (soft delete).')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp del borrado lógico. NULL = registro activo.', null=True)),
                ('data', models.BinaryField(help_text='JSON del vocabulario comprimido con gzip.')),
                ('lemma_count', models.PositiveIntegerField(default=0, help_text='Palabras distintas (lemas).')),
                ('word_count', models.PositiveIntegerField(default=0, help_text='Apariciones contadas en el libro.')),
                ('engine', models.CharField(blank=True, default='', help_text='Modelo que hizo el análisis.', max_length=80)),
                ('format_version', models.PositiveSmallIntegerField(default=1)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='catalog.book')),
            ],
            options={
                'verbose_name': 'Book Vocabulary',
                'verbose_name_plural': 'Book Vocabularies',
            },
        ),
    ]
