# Generated by Django 6.0.4 on 2026-09-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0022_book_catalog_boo_is_publ_5fcf8b_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="author",
            index=models.Index(
                fields=["full_name"], name="catalog_aut_full_na_9e8869_idx"
            ),
        ),
    ]
