# Generated by Django 6.0.4 on 2026-10-04 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_book_vocabulary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='editorial_notes',
            field=models.TextField(blank=True, default='', help_text='Observaciones, sugerencias o motivos editoriales del Administrador.'),
        ),
        migrations.AddField(
            model_name='book',
            name='submission_declaration',
            field=models.BooleanField(default=False, help_text='Declaración jurada de autoría o derechos legítimos.'),
        ),
        migrations.AddField(
            model_name='book',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='Usuario o autor que remitió la obra para curaduría.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending_review', 'En Revisión'), ('published', 'Publicado'), ('rejected', 'Rechazado'), ('archived', 'Archivado')], default='draft', help_text='Estado de la obra en el flujo de trabajo.', max_length=20),
        ),
    ]
