# Generated by Django 6.0.4 on 2026-10-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_book_editorial_notes_book_submission_declaration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='min_age',
            field=models.PositiveSmallIntegerField(default=0, help_text='Edad mínima recomendada para leer la obra (0 = para todo público).'),
        ),
    ]
