# Generated by Django 6.0.4 on 2026-10-07 22:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_book_min_age'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal. Ver documentación de diseño para justificación.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación. Inmutable post-creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación. Gestionado automáticamente.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indica un registro borrado lógicamente (soft delete).')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp del borrado lógico. NULL = registro activo.', null=True)),
                ('status', models.CharField(choices=[('generating', 'Generando'), ('ready', 'Listo'), ('failed', 'Falló')], default='generating', max_length=12)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('model_name', models.CharField(blank=True, default='', max_length=60)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary', to='catalog.book')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book Summary',
                'verbose_name_plural': 'Book Summaries',
            },
        ),
    ]
