# Generated by Django 6.0.4 on 2026-10-10 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_classify_adult_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterProgressSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal. Ver documentación de diseño para justificación.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación. Inmutable post-creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación. Gestionado automáticamente.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indica un registro borrado lógicamente (soft delete).')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp del borrado lógico. NULL = registro activo.', null=True)),
                ('up_to_chapter', models.PositiveIntegerField(help_text='Hasta qué capítulo cubre este resumen (inclusive).')),
                ('status', models.CharField(choices=[('generating', 'Generando'), ('ready', 'Listo'), ('failed', 'Falló')], default='generating', max_length=12)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('model_name', models.CharField(blank=True, default='', max_length=60)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progress_summaries', to='catalog.book')),
            ],
            options={
                'verbose_name': 'Chapter Progress Summary',
                'verbose_name_plural': 'Chapter Progress Summaries',
                'ordering': ['book', 'up_to_chapter'],
                'constraints': [models.UniqueConstraint(fields=('book', 'up_to_chapter'), name='unique_book_chapter_progress_summary', violation_error_message='Este libro ya tiene un resumen registrado para ese capítulo.')],
            },
        ),
    ]
