# Generated by Django 6.0.4 on 2026-09-04 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0012_remove_aiavatar_image_speaking_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "-updated_at"], name="ai_engine_ch_user_updated_idx"
            ),
        ),
    ]
