# Generated by Django 6.0.4 on 2026-09-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0012_remove_aiavatar_image_speaking_and_more'),
        ('catalog', '0021_alter_genre_cover_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aiavatar',
            index=models.Index(fields=['name'], name='aiavatar_name_idx'),
        ),
        migrations.AddIndex(
            model_name='aiavatar',
            index=models.Index(fields=['-chat_count', 'name'], name='aiavatar_popular_idx'),
        ),
    ]
