# Generated by Django 6.0.4 on 2026-09-30 23:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0014_assistantconversation_assistantmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('tokens_reserved', models.PositiveIntegerField(default=0)),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('accounted_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIUsageEvent',
            fields=[
                ('request_id', models.UUIDField(primary_key=True, serialize=False)),
                ('message_hash', models.CharField(max_length=64)),
                ('mode', models.CharField(max_length=10)),
                ('status', models.CharField(default='reserved', max_length=20)),
                ('reserved_tokens', models.PositiveIntegerField(default=0)),
                ('ink_cost', models.PositiveSmallIntegerField(default=0)),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('reasoning_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('attempts', models.JSONField(default=list)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_engine.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ai_engine.dailyaiusage')),
            ],
        ),
        migrations.CreateModel(
            name='InkChatQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_hash', models.CharField(max_length=64)),
                ('ink_cost', models.PositiveSmallIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_engine.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIActivityLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField()),
                ('expires_at', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_engine.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'client_id'), name='unique_ai_activity_client')],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyaiusage',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_ai_usage'),
        ),
        migrations.AddIndex(
            model_name='aiusageevent',
            index=models.Index(fields=['user', 'created_at'], name='ai_engine_a_user_id_72a153_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusageevent',
            index=models.Index(fields=['status', 'expires_at'], name='ai_engine_a_status_b3285b_idx'),
        ),
    ]
