# Generated by Django 6.0.4 on 2026-09-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0015_dailyaiusage_aiusageevent_inkchatquote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyaiusage',
            name='quota_exhausted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
