# Generated by Django 6.0.4 on 2026-10-01 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0016_dailyaiusage_quota_exhausted_at'),
        ('finance', '0008_paypalsubscriptionbinding_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusageevent',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.subscriptionplan'),
        ),
    ]
