# Generated by Django 6.0.4 on 2026-10-04 22:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0017_aiusageevent_subscription_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlindInterrogationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal. Ver documentación de diseño para justificación.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación. Inmutable post-creación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación. Gestionado automáticamente.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indica un registro borrado lógicamente (soft delete).')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp del borrado lógico. NULL = registro activo.', null=True)),
                ('distractor_avatar_ids', models.JSONField(default=list, help_text='IDs de los 3 avatares señuelo.')),
                ('candidate_order', models.JSONField(default=list, help_text='Lista ordenada de IDs de los 4 candidatos mostrados al usuario.')),
                ('questions_allowed', models.PositiveIntegerField(default=3)),
                ('questions_used', models.PositiveIntegerField(default=0)),
                ('extra_questions_bought', models.PositiveIntegerField(default=0)),
                ('clues_bought', models.PositiveIntegerField(default=0)),
                ('discarded_avatar_ids', models.JSONField(default=list, help_text='Avatares descartados por ventaja de 50/50.')),
                ('dialogue_history', models.JSONField(default=list, help_text="Lista de mensajes: [{'role': 'user'|'character'|'clue', 'content': '...'}]")),
                ('status', models.CharField(choices=[('playing', 'En juego'), ('won', 'Descubierto con éxito'), ('lost', 'No descubierto / Fallado'), ('abandoned', 'Abandonado')], default='playing', max_length=20)),
                ('ink_earned', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('is_official_daily', models.BooleanField(default=True)),
                ('game_date', models.DateField(default=django.utils.timezone.localdate)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ai_engine.aiavatar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blind Interrogation Session',
                'verbose_name_plural': 'Blind Interrogation Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
